<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Leaderboard\**" />
    <Compile Remove="ProducerConsumer\**" />
    <Compile Remove="RetryMechanism\**" />
    <Compile Remove="SnapshotProcessOfflock\**" />
    <Compile Remove="TTLEviction\**" />
    <EmbeddedResource Remove="Leaderboard\**" />
    <EmbeddedResource Remove="ProducerConsumer\**" />
    <EmbeddedResource Remove="RetryMechanism\**" />
    <EmbeddedResource Remove="SnapshotProcessOfflock\**" />
    <EmbeddedResource Remove="TTLEviction\**" />
    <None Remove="Leaderboard\**" />
    <None Remove="ProducerConsumer\**" />
    <None Remove="RetryMechanism\**" />
    <None Remove="SnapshotProcessOfflock\**" />
    <None Remove="TTLEviction\**" />
  </ItemGroup>

</Project>
